#!/usr/bin/env python3
"""Fetch the human-readable star-name catalogue used by First Light.

Source: Wikipedia's List of proper names of stars, which collates IAU Working
Group on Star Names / NameExoWorlds names. The source's CC BY-SA attribution
requirements apply to the generated data. Run from this workspace:
    pnpm --filter @vela/web refresh-stars
"""
import html
import json
import re
import urllib.parse
import urllib.request
from html.parser import HTMLParser
from pathlib import Path

URL = "https://en.wikipedia.org/w/api.php?" + urllib.parse.urlencode({
    "action": "parse",
    "page": "List_of_proper_names_of_stars",
    "prop": "text",
    "format": "json",
    "origin": "*",
})

class TableRows(HTMLParser):
    def __init__(self):
        super().__init__()
        self.rows, self.row, self.cell, self.cell_depth = [], None, None, 0

    def handle_starttag(self, tag, attrs):
        if tag == "tr":
            self.row = []
        elif tag in ("td", "th") and self.row is not None:
            self.cell, self.cell_depth = [], 1
        elif self.cell is not None:
            self.cell_depth += 1

    def handle_endtag(self, tag):
        if tag in ("td", "th") and self.cell is not None:
            self.row.append("".join(self.cell).strip())
            self.cell, self.cell_depth = None, 0
        elif tag == "tr" and self.row is not None:
            self.rows.append(self.row)
            self.row = None
        elif self.cell is not None:
            self.cell_depth -= 1

    def handle_data(self, data):
        if self.cell is not None:
            self.cell.append(data)

def clean(value):
    return re.sub(r"\s+", " ", html.unescape(value)).strip()

def is_single_word(name):
    # Keep diacritics, apostrophes, and hyphens; reject phrases and catalog IDs.
    return bool(re.fullmatch(r"[^\W\d_][\w'’\-]*", name, flags=re.UNICODE))

def main():
    request = urllib.request.Request(
        URL,
        headers={"User-Agent": "FirstLightNameFinder/1.0 (personal project)"},
    )
    with urllib.request.urlopen(request) as response:
        markup = json.load(response)["parse"]["text"]["*"]
    parser = TableRows()
    parser.feed(markup)
    seen, stars = set(), []

    for row in parser.rows:
        if len(row) < 4:
            continue
        name, designation, constellation, origin = map(clean, row[:4])
        name = re.sub(r"[†‡*]+$", "", name).strip()
        if not is_single_word(name) or name in seen or name == "Name":
            continue
        # The page's star table uses a constellation and cultural-origin column.
        if not constellation or not origin or constellation in {"Constellation", "Origin"}:
            continue
        seen.add(name)
        stars.append({
            "name": name,
            "reference": f"{designation} — {constellation}",
            "origin": origin,
        })

    stars.sort(key=lambda star: star["name"].casefold())
    output = Path(__file__).resolve().parents[1] / "public" / "data" / "iau-named-stars.js"
    output.parent.mkdir(exist_ok=True)
    output.write_text(
        "// Generated by scripts/refresh_iau_stars.py; do not edit by hand.\n"
        "// Source: Wikipedia, List of proper names of stars (CC BY-SA 4.0), accessed 2026-08-15.\n"
        "window.IAU_NAMED_STARS = " + json.dumps(stars, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(stars)} single-word proper star names to {output}")

if __name__ == "__main__":
    main()
