// Sample values for judging the interaction, not an ephemeris or calibrated sky survey.
export const targets = [
  {
    id: 'm13',
    name: 'Hercules Cluster',
    catalog: 'M13 · NGC 6205',
    kind: 'Globular cluster',
    description: 'A dense globe of stars, with a bright heart and scattered outer stars.',
    image: new URL('./m13.jpg', import.meta.url).href,
    source: 'https://noirlab.edu/public/images/noao-m13bash2/',
    credit: 'KPNO/NOIRLab/NSF/AURA/Tom Bash and John Fox/Adam Block',
    window: 'Earlier in the evening',
    peak: 54,
    culmination: 90,
  },
  {
    id: 'crescent',
    name: 'Crescent Nebula',
    catalog: 'NGC 6888',
    kind: 'Emission nebula',
    description: 'A delicate shell of glowing gas against a crowded field of stars.',
    image: new URL('./crescent.jpg', import.meta.url).href,
    source: 'https://noirlab.edu/public/images/noao-04494/',
    credit: 'T.A. Rector (NRAO/AUI/NSF and NOIRLab/NSF/AURA)',
    window: 'High through midnight',
    peak: 76,
    culmination: 164,
  },
  {
    id: 'andromeda',
    name: 'Andromeda Galaxy',
    catalog: 'M31 · NGC 224',
    kind: 'Spiral galaxy',
    description: 'A luminous core, sweeping dust lanes, and two companion galaxies.',
    image: new URL('./andromeda.jpg', import.meta.url).href,
    source: 'https://esahubble.org/images/heic1502b/',
    credit: 'NASA, ESA, Digitized Sky Survey 2 (Acknowledgement: Davide De Martin)',
    window: 'Better later tonight',
    peak: 68,
    culmination: 235,
  },
]
