export type {
  DeviceKind as AlpacaDeviceKind,
  ConnectionStatus as AlpacaConnectionStatus,
  DeviceConnectionResult as AlpacaDeviceConnectionResult,
  EquipmentDevice as AlpacaDevice,
  TelemetryAvailability as AlpacaTelemetryAvailability,
  CameraActivity as AlpacaCameraActivity,
  DeviceTelemetry as AlpacaDeviceTelemetry,
  SwitchChannel as AlpacaSwitchChannel,
  EquipmentInspection as AlpacaDeviceInspection
} from '@vela/equipment'
