"""Generate the bundled catalog; Python standard library only, no runtime network."""
import csv
import hashlib
import io
import json
import math
from pathlib import Path
import re
import urllib.request

PIN = 'da90466031b0372c896588b85be6016c617e205b'
SOURCES = {
  'NGC.csv': 'be150bdaa1997dacbcb39f303074403edec7a953b589b36d5f1c4522c0cc6fae',
  'addendum.csv': '1d8f0914e643ada325a5a94d88d8fefad6a4937a2f77cc34f21483af22b11983',
}
TYPES = {
  '*': 'Star',
  '**': 'Double star',
  '*Ass': 'Association of stars',
  'OCl': 'Open cluster',
  'GCl': 'Globular cluster',
  'Cl+N': 'Star cluster and nebula',
  'G': 'Galaxy',
  'GPair': 'Galaxy pair',
  'GTrpl': 'Galaxy triplet',
  'GGroup': 'Galaxy group',
  'PN': 'Planetary nebula',
  'HII': 'H II region',
  'DrkN': 'Dark nebula',
  'EmN': 'Emission nebula',
  'Neb': 'Nebula',
  'RfN': 'Reflection nebula',
  'SNR': 'Supernova remnant',
  'Nova': 'Nova',
  'Other': 'Other',
}
# These names refer to the retained source record, not a replacement position or size.
# Evidence and the erroneous IC0434 aliases are recorded in README.md.
EXTRA_NAMES = {
  'NGC6205': ['Great Hercules Cluster', 'Great Globular Cluster in Hercules'],
  'IC1805': ['Heart Nebula'],
  'IC1848': ['Soul Nebula', 'Embryo Nebula'],
  'NGC2024': ['Flame Nebula'],
  'B033': ['Barnard 33'],
}


def coordinate(value, ra):
  pattern = r'\d{2}:\d{2}:\d{2}(?:\.\d+)?' if ra else r'[+-]\d{2}:\d{2}:\d{2}(?:\.\d+)?'
  if not re.fullmatch(pattern, value):
    raise ValueError(f'Invalid coordinate: {value}')
  first, minute, second = map(float, value.lstrip('+-').split(':'))
  maximum = 24 if ra else 90
  if minute >= 60 or second >= 60 or first > maximum or (first == maximum and (ra or minute or second)):
    raise ValueError(f'Out-of-range coordinate: {value}')
  result = (first + minute / 60 + second / 3600) * (15 if ra else 1)
  return round(-result if value.startswith('-') else result, 8)


def extent(value):
  if not value:
    return None
  result = float(value)
  if not math.isfinite(result) or result <= 0:
    raise ValueError(f'Invalid angular extent: {value}')
  return result


def designation(value):
  match = re.fullmatch(r'(NGC|IC|M|B)0*(\d+)(.*)', value)
  return f'{match[1]} {int(match[2])}{match[3]}' if match else value


def normalize(row):
  if row['Type'] in ('Dup', 'NonEx'):
    return None
  if not row['RA'] and not row['Dec']:
    return None
  name = row['Name']
  common = [v.strip() for v in row['Common names'].split(',') if v.strip()]
  if name == 'IC0434':
    common = [v for v in common if v not in ('Flame Nebula', 'Orion B')]
  common += EXTRA_NAMES.get(name, [])
  aliases = [name, designation(name)]
  for prefix in ['M', 'NGC', 'IC']:
    for number in row[prefix].split(','):
      if number.strip():
        aliases.append(designation(prefix + number.strip()))
  aliases += common
  return [
    name.lower(),
    designation(name),
    common[0] if common else None,
    list(dict.fromkeys(aliases)),
    coordinate(row['RA'], True),
    coordinate(
      '+07:13:00.0' if name == 'IC3322A' and row['Dec'] == '+07:12:60.0' else row['Dec'],
      False,
    ),
    TYPES[row['Type']],
    extent(row['MajAx']),
    extent(row['MinAx']),
  ]


def generate():
  targets = []
  for name, digest in SOURCES.items():
    url = f'https://raw.githubusercontent.com/mattiaverga/OpenNGC/{PIN}/database_files/{name}'
    data = urllib.request.urlopen(url, timeout=30).read()
    if hashlib.sha256(data).hexdigest() != digest:
      raise ValueError(f'Source checksum mismatch: {name}')
    for row in csv.DictReader(io.StringIO(data.decode('utf-8')), delimiter=';'):
      try:
        target = normalize(row)
      except (ValueError, KeyError) as error:
        raise ValueError(f'{name}: {row["Name"]}: {error}') from error
      if target:
        targets.append(target)
  targets.sort(key=lambda row: row[0])
  if len({row[0] for row in targets}) != len(targets):
    raise ValueError('Duplicate target IDs')
  header = ('// Generated by generate.py from OpenNGC; see README.md for provenance.\n'
            '// SPDX-License-Identifier: CC-BY-SA-4.0\n'
            "import type { CatalogRow } from './types.js'\n\n"
            'export const catalogRows: readonly CatalogRow[] = [\n')
  lines = [json.dumps(row, ensure_ascii=True, separators=(',', ':')) for row in targets]
  Path(__file__).with_name('data.ts').write_text(header + ',\n'.join(lines) + '\n]\n')
  print(f'Generated {len(targets)} targets')


if __name__ == '__main__':
  generate()
